<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit77a936995b521a4e16cb596ebdcb46ed
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\JourneyPins\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\JourneyPins\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit77a936995b521a4e16cb596ebdcb46ed::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit77a936995b521a4e16cb596ebdcb46ed::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit77a936995b521a4e16cb596ebdcb46ed::$classMap;

        }, null, ClassLoader::class);
    }
}
